-- MySQL Script generated by MySQL Workbench
-- Sat 30 Mar 2024 11:39:19 PM MSK
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema cart
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cart
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cart` DEFAULT CHARACTER SET utf8 ;
USE `cart` ;

-- -----------------------------------------------------
-- Table `cart`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cart`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cart`.`storage`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cart`.`storage` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `price` DECIMAL(10,2) NOT NULL,
  `amount` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cart`.`cart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cart`.`cart` (
  `user_id` INT NOT NULL,
  `storage_id` INT NOT NULL,
  `amount` INT NOT NULL,
  INDEX `user_id_idx` (`user_id` ASC) VISIBLE,
  INDEX `storage_id_idx` (`storage_id` ASC) VISIBLE,
  CONSTRAINT `user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `cart`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `storage_id`
    FOREIGN KEY (`storage_id`)
    REFERENCES `cart`.`storage` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
